//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.BILLs = new HashSet<BILL>();
            this.IMPORTED_COUPON_BR = new HashSet<IMPORTED_COUPON_BR>();
            this.IMPORTED_COUPON_HQ = new HashSet<IMPORTED_COUPON_HQ>();
            this.PROPOSED_IMPORT_COUPON = new HashSet<PROPOSED_IMPORT_COUPON>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string house { get; set; }
        public string street { get; set; }
        public string township { get; set; }
        public string city { get; set; }
        public string mobilephone { get; set; }
        public string idcard { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string permission { get; set; }
    
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual ICollection<IMPORTED_COUPON_BR> IMPORTED_COUPON_BR { get; set; }
        public virtual ICollection<IMPORTED_COUPON_HQ> IMPORTED_COUPON_HQ { get; set; }
        public virtual ICollection<PROPOSED_IMPORT_COUPON> PROPOSED_IMPORT_COUPON { get; set; }
    }
}
