//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public BILL()
        {
            this.BILL_DETAIL = new HashSet<BILL_DETAIL>();
        }
    
        public string id { get; set; }
        public string accountid { get; set; }
        public System.DateTime date { get; set; }
        public string pos { get; set; }
        public int totalprice { get; set; }
        public int totalamount { get; set; }
        public int cusprice { get; set; }
        public int rejectprice { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<BILL_DETAIL> BILL_DETAIL { get; set; }
    }
}
