//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTED_COUPON_HQ
    {
        public IMPORTED_COUPON_HQ()
        {
            this.IMPORTED_COUPON_BR = new HashSet<IMPORTED_COUPON_BR>();
            this.IMPORTED_COUPON_HQ_DETAIL = new HashSet<IMPORTED_COUPON_HQ_DETAIL>();
        }
    
        public string id { get; set; }
        public string proposedid { get; set; }
        public string accountid { get; set; }
        public System.DateTime date { get; set; }
        public int totalprice { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<IMPORTED_COUPON_BR> IMPORTED_COUPON_BR { get; set; }
        public virtual ICollection<IMPORTED_COUPON_HQ_DETAIL> IMPORTED_COUPON_HQ_DETAIL { get; set; }
        public virtual PROPOSED_IMPORT_COUPON PROPOSED_IMPORT_COUPON { get; set; }
    }
}
