//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTED_COUPON_BR
    {
        public IMPORTED_COUPON_BR()
        {
            this.IMPORTED_COUPON_BR_DETAIL = new HashSet<IMPORTED_COUPON_BR_DETAIL>();
        }
    
        public string id { get; set; }
        public string imcouphqid { get; set; }
        public string accountid { get; set; }
        public System.DateTime date { get; set; }
        public int branch { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<IMPORTED_COUPON_BR_DETAIL> IMPORTED_COUPON_BR_DETAIL { get; set; }
        public virtual IMPORTED_COUPON_HQ IMPORTED_COUPON_HQ { get; set; }
    }
}
