//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TYPE
    {
        public PRODUCT_TYPE()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public int amount { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
    }
}
