//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.BILL_DETAIL = new HashSet<BILL_DETAIL>();
            this.HISTORICAL_PRICE = new HashSet<HISTORICAL_PRICE>();
            this.IMPORTED_COUPON_BR_DETAIL = new HashSet<IMPORTED_COUPON_BR_DETAIL>();
            this.IMPORTED_COUPON_HQ_DETAIL = new HashSet<IMPORTED_COUPON_HQ_DETAIL>();
            this.PROMO_INFO = new HashSet<PROMO_INFO>();
            this.PROPOSED_IMPORT_COUPON_DETAIL = new HashSet<PROPOSED_IMPORT_COUPON_DETAIL>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string picture { get; set; }
        public string supplierid { get; set; }
        public string producttypeid { get; set; }
    
        public virtual ICollection<BILL_DETAIL> BILL_DETAIL { get; set; }
        public virtual ICollection<HISTORICAL_PRICE> HISTORICAL_PRICE { get; set; }
        public virtual ICollection<IMPORTED_COUPON_BR_DETAIL> IMPORTED_COUPON_BR_DETAIL { get; set; }
        public virtual ICollection<IMPORTED_COUPON_HQ_DETAIL> IMPORTED_COUPON_HQ_DETAIL { get; set; }
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual ICollection<PROMO_INFO> PROMO_INFO { get; set; }
        public virtual ICollection<PROPOSED_IMPORT_COUPON_DETAIL> PROPOSED_IMPORT_COUPON_DETAIL { get; set; }
    }
}
