//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMO_INFO
    {
        public string id { get; set; }
        public string producid { get; set; }
        public int price { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string promocontent { get; set; }
        public string picture { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
