//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM6_CMART
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSED_IMPORT_COUPON_DETAIL
    {
        public string proposedid { get; set; }
        public string productid { get; set; }
        public int amount { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROPOSED_IMPORT_COUPON PROPOSED_IMPORT_COUPON { get; set; }
    }
}
